### ISSUE TITLE
Add separate repo/resource of lots of manpages + deroffed + fish completions

### ISSUE THREAD

**Issue by scooter-dangle** [rust-dc/fish-manpage-completions#25]
Follow-on to #7, but we don't want to fill up _this_ repo with examples.

**Comment by kbknapp** [comment]
https://github.com/kbknapp/manpages

I can transfer to rust-dc if this meets the criteria. Some stuff to still do is maybe print the verbose output of each generate? Because there is some good info in that, and also some of the manpages parse out to "non-command-line manpages" so maybe a list of those too. Just ideas.

**Comment by scooter-dangle** [comment]
Seems like a good corpus to start from. Do you need anything from me to be able to transfer over the repo?

**Comment by kbknapp** [comment]
Nope, just transferred it :smile:

**Comment by scooter-dangle** [comment]
Awesome...thanks!
